### ISSUE TITLE
Srcolling to content area instead to images?

### ISSUE THREAD

**Issue by jonas-landeck** [strarsis/twentyseventeen-onepage#1]
Hello people, hello strarsis,
thanks to this community and strarsis for your work. I really appreciate what is going on here.
I am very new to programming and this platform, so forgive me my mistakes please.

I would love to implement the twenty seventeen theme as a "one page". Unfortunately i was after days not able to figure out how i possibly could change where the scrolling effect stops on the site. 
I wish it would be the content area displayed, instead of the image area.
Sorry, i am lost and rlly need help.
My Website: http://all-mende.de
I also wonder why the scrolling effect doesen't work for the "Home section".

Many, many Thanks!
Sqiek

**Comment by strarsis** [comment]
@Sqiek: On first glance it appears that on that site the anchor for the home section button is empty, the link is just [#](#) - you have to link the anchor named after the slug of the home page which is 'startseite'. So you have to modify the menu item for Home and change it to '#startseite'.

**Comment by jonas-landeck** [comment]
Hey strarsis. 
Thanks alot for the help and fast reply, I really appreciate it.
I will look into this. 
Do you may be have a solution for the first issue? I need the scroll effect to stop at the content (text) area. At the moment it stops where the image is. 

Thanks and best regards. 
Sqiek

**Comment by strarsis** [comment]
@Sqiek: It depends on where the element with the ID (=anchor) begins. 
The browser will scroll up until the top of element is at viewport edge.
You can adjust height/position of the element that acts as anchor using CSS.

Edit: The article element gets the ID (slug) to which should be scrolled.
When a background image is used like on this site, there is extra spacing added to the article element.

**Comment by strarsis** [comment]
@Sqiek: Were you able to solve this issue

**Comment by jonas-landeck** [comment]
@strarsis Hello strarsis, thanks for your reply and sorry for the late answer. 
I was now able to solve issue #1 but wasn't able to solve issue #2 (scroll to content area).
Unfortunately I don't know where to modify the code without destroying the layout completely.
For specific section areas (where pictures are inserted), i need to make the webpage let scroll to the content area. I am confused :/  .. Thx in advance. Sqiek.

**Comment by strarsis** [comment]
@Sqiek: I modified this theme for having the anchor IDs assigned to content element in article instead, 
this should fix the offset. Maybe it is more elegant to leave the anchor ID for the article and use some kind of offset - but this would complicate the existing styles.

**Comment by jonas-landeck** [comment]
Thank you @strarsis , i cannot describe how thankful i am. Absolutely stunning support. I appreciate that.
It looks almost just fine but it somehow covers the headings a tiny bit, they are not completely in viewport. 
Actually it would be great if you could see the the headings  completely and furthermore a small stripe of the image above. I will look into that tomorrow, maybe i will be able to figure it on my own now.

**Comment by strarsis** [comment]
@Sqiek: I guess you were able to resolve the issue.
When you still have questions, feel free to ask them here.
