### ISSUE TITLE
Expand README.md

### ISSUE THREAD

**Issue by nydeggerm** [strarsis/twentyseventeen-onepage#3]
Thanks for the great work!!!

I had some problem to implement the Theme. In the end I got it work. :-)

Maybe you could expand the "Setup" section in the README.md as following:
1. Create single pages for every section you want
2. Open Theme Customizer: Define the "Static Front Page" with the page which should be shown as the first section
3. Open Theme Customizer: Open "Theme options" and define your sections.
   if more then 4 sections are needed do the following: https://github.com/strarsis/twentyseventeen-onepage/issues/2
4. Open the Menu configuration and dreate a new Menu
   Choose "Individual Links". URL="#pageslug"; Link Text="<Name of the section which you want to show>"
   The "page-slug" is showing on every Page directly after the input field for the page title ("Permalink:"). The "page slug" is the last part
   example: http://test.domain.com/page-1 -> "page-1" -> URL="#page-1"
5. Install the Wordpress-Plugin "jQuery Smooth Scroll" https://wordpress.org/plugins/jquery-smooth-scroll/

**Comment by strarsis** [comment]
@nydeggerm: Thank you for your improvements. I added them to the [README](https://github.com/strarsis/twentyseventeen-onepage/blob/master/README.md#setup). 
Are further additions or changes to README needed?

**Comment by nydeggerm** [comment]
That was quick. Thanks.
At the moment, everything is fine. I have no more additions. :-)
